# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-rcpparmadillo r-cran-bh r-cran-runit r-cran-kernsmooth r-cran-class r-cran-nnet
  
script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
    - Rscript -e 'covr::codecov()'
    
    